/**
 * vault-dashboard — renders `Dashboard.md`, the vault's test-coverage overview.
 *
 * Generated, like `Automated Tests/`: vault-lint --fix writes it from the vault
 * and the tests, and vault-lint fails while it is out of date. Nothing in it is
 * a fact of its own, so nothing in it is edited by hand.
 *
 * Charts are Mermaid, which Obsidian renders natively. Colours follow the
 * dataviz method: three categorical slots validated all-pairs for colour-vision
 * deficiency on both the light and the dark surface (one set, since a note
 * cannot switch palettes with the theme), a muted grey for "other", and every
 * slice labelled with an icon and its value so colour never carries meaning
 * alone. A ratio against a whole is a meter, not a two-slice pie.
 */

/** Categorical slots 1–3 (dark steps: they pass on both surfaces), then the muted grey. */
const SLOTS = ['#3987e5', '#d95926', '#199e70'];
const MUTED = '#898781';

export interface DashboardInput {
    /** Module hub name → display name, e.g. `members-roles` → `Members & Roles`. */
    modules: Map<string, string>;
    requirements: { name: string; module?: string }[];
    testCases: {
        name: string;
        requirement: string;
        module?: string;
        type: string;
        state: 'approved' | 'draft' | 'rejected';
    }[];
    tests: {
        note: string;
        mode: 'test' | 'fixme' | 'skip';
        covers: string[];
        stale: string[];
    }[];
}

interface Slice {
    label: string;
    value: number;
    color: string;
}

/**
 * A Mermaid pie. Mermaid orders slices by size and colours them in that order,
 * so a slice's colour would follow its rank; emitting them pre-sorted with the
 * palette in the same order keeps each colour on its category instead.
 */
function pie(title: string, slices: Slice[]): string {
    const shown = slices
        .filter((slice) => slice.value > 0)
        .map((slice, order) => ({ ...slice, order }))
        .sort((a, b) => b.value - a.value || a.order - b.order);
    const colors = Object.fromEntries(
        shown.map((slice, index) => [`pie${index + 1}`, slice.color]),
    );
    const init = JSON.stringify({
        // Full opacity, so a slice matches its legend swatch and the validated
        // colour; a thin neutral stroke that reads on both surfaces.
        themeVariables: {
            ...colors,
            pieOpacity: '1',
            pieStrokeColor: MUTED,
            pieStrokeWidth: '1px',
            pieOuterStrokeColor: MUTED,
            pieOuterStrokeWidth: '1px',
        },
    });
    return [
        '```mermaid',
        `%%{init: ${init}}%%`,
        `pie showData title ${title}`,
        ...shown.map((slice) => `    "${slice.label}" : ${slice.value}`),
        '```',
    ].join('\n');
}

/** `█████░░░░░ 50%` — a ten-cell meter for a ratio against a whole. */
function meter(part: number, whole: number): string {
    if (whole === 0) return '—';
    const ratio = part / whole;
    const filled = Math.round(ratio * 10);
    return `\`${'█'.repeat(filled)}${'░'.repeat(10 - filled)}\` ${Math.round(ratio * 100)}%`;
}

function link(name: string, display?: string): string {
    return display ? `[[${name}\\|${display}]]` : `[[${name}]]`;
}

/** A Mermaid node id: letters, digits and underscores only. */
function nodeId(prefix: string, name: string): string {
    return `${prefix}_${name.replace(/[^A-Za-z0-9]/g, '_')}`;
}

/** A Mermaid label: double quotes are the only character it cannot hold. */
function label(text: string): string {
    return `"${text.replace(/"/g, '#quot;')}"`;
}

function callout(kind: string, title: string, items: string[]): string {
    return [`> [!${kind}]- ${title}`, ...items.map((item) => `> - ${item}`)].join('\n');
}

export function renderDashboard(input: DashboardInput): string {
    const { modules, requirements, testCases, tests } = input;
    const running = tests.filter((test) => test.mode === 'test');
    const automated = new Set(running.flatMap((test) => test.covers));
    const approved = testCases.filter((tc) => tc.state === 'approved');
    const approvedAutomated = approved.filter((tc) => automated.has(tc.name));
    const coveredRequirements = new Set(approvedAutomated.map((tc) => tc.requirement));
    const traced = tests.filter((test) => test.covers.length > 0);
    const stale = tests.filter((test) => test.stale.length > 0);
    const notRunning = tests.filter((test) => test.mode !== 'test');

    const out: string[] = [];
    out.push('---', 'tags:', '  - kind/dashboard', '---', '');
    out.push('# Test dashboard', '');
    out.push(
        'Generated by `npm.cmd run vault:lint -- --fix` from the vault and the tests; ' +
            'the lint fails while it is out of date. A test case counts as automated when a ' +
            'running test (not fixme or skip) covers it.',
        '',
    );

    // ------------------------------------------------------------ headline
    out.push('## At a glance', '');
    out.push('| Measure | Coverage | Count |', '| --- | --- | --- |');
    out.push(
        `| Requirements with an automated test | ${meter(coveredRequirements.size, requirements.length)} | ${coveredRequirements.size} of ${requirements.length} |`,
        `| Test cases approved | ${meter(approved.length, testCases.length)} | ${approved.length} of ${testCases.length} |`,
        `| Approved test cases automated | ${meter(approvedAutomated.length, approved.length)} | ${approvedAutomated.length} of ${approved.length} |`,
        `| Tests traced to a test case | ${meter(traced.length, tests.length)} | ${traced.length} of ${tests.length} |`,
        `| Stale tests | ${stale.length ? '⚠️' : '✅'} | ${stale.length} |`,
        `| Tests marked fixme or skip | ${notRunning.length ? '⏸️' : '✅'} | ${notRunning.length} |`,
        '',
    );

    // --------------------------------------------------------- by module
    const moduleNames = [...modules.keys()].sort((a, b) =>
        (modules.get(a) ?? a).localeCompare(modules.get(b) ?? b),
    );
    out.push('## Coverage by module', '');
    const percent = moduleNames.map((module) => {
        const cases = approved.filter((tc) => tc.module === module);
        const done = cases.filter((tc) => automated.has(tc.name)).length;
        return cases.length ? Math.round((done / cases.length) * 100) : 0;
    });
    out.push(
        '```mermaid',
        `%%{init: ${JSON.stringify({ themeVariables: { xyChart: { plotColorPalette: SLOTS[0] } } })}}%%`,
        'xychart-beta',
        '    title "Approved test cases automated (%)"',
        `    x-axis [${moduleNames.map((module) => label(modules.get(module) ?? module)).join(', ')}]`,
        '    y-axis "Automated (%)" 0 --> 100',
        `    bar [${percent.join(', ')}]`,
        '```',
        '',
    );
    out.push(
        '| Module | Requirements | Test cases | Approved | Automated | Coverage | Tests | Stale |',
        '| --- | --: | --: | --: | --: | --- | --: | --: |',
    );
    for (const module of moduleNames) {
        const cases = testCases.filter((tc) => tc.module === module);
        const moduleApproved = cases.filter((tc) => tc.state === 'approved');
        const moduleAutomated = moduleApproved.filter((tc) => automated.has(tc.name));
        const ids = new Set(cases.map((tc) => tc.name));
        const moduleTests = tests.filter((test) => test.covers.some((id) => ids.has(id)));
        out.push(
            `| ${link(module, modules.get(module))} | ${requirements.filter((r) => r.module === module).length} ` +
                `| ${cases.length} | ${moduleApproved.length} | ${moduleAutomated.length} ` +
                `| ${meter(moduleAutomated.length, moduleApproved.length)} | ${moduleTests.length} ` +
                `| ${moduleTests.filter((test) => test.stale.length).length} |`,
        );
    }
    out.push('');

    // ------------------------------------------------------------- pies
    out.push('## Test cases', '');
    const states: Slice[] = [
        { label: '✅ Approved', value: approved.length, color: SLOTS[0] },
        {
            label: '✏️ Draft',
            value: testCases.filter((tc) => tc.state === 'draft').length,
            color: SLOTS[1],
        },
        {
            label: '❌ Rejected',
            value: testCases.filter((tc) => tc.state === 'rejected').length,
            color: SLOTS[2],
        },
    ];
    if (states.filter((slice) => slice.value > 0).length > 1) {
        out.push(pie('Review state', states), '');
    } else {
        out.push(
            `All ${testCases.length} test cases are ${states.find((s) => s.value)?.label ?? '—'}.`,
            '',
        );
    }

    // Types: the three largest keep a slot each, the rest fold into Other.
    const byType = new Map<string, number>();
    testCases.forEach((tc) => byType.set(tc.type, (byType.get(tc.type) ?? 0) + 1));
    const ranked = [...byType].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    const types: Slice[] = ranked
        .slice(0, 3)
        .map(([type, count], index) => ({ label: type, value: count, color: SLOTS[index] }));
    const other = ranked.slice(3);
    if (other.length) {
        types.push({
            label: `other (${other.length} types)`,
            value: other.reduce((sum, [, count]) => sum + count, 0),
            color: MUTED,
        });
    }
    out.push(pie('By type', types), '');

    out.push('## Automated tests', '');
    out.push(
        pie('Traceability', [
            { label: '🔗 Traced, current', value: traced.length - stale.length, color: SLOTS[0] },
            { label: '⚠️ Traced, stale', value: stale.length, color: SLOTS[1] },
            { label: '○ Not traced', value: tests.length - traced.length, color: MUTED },
        ]),
        '',
    );

    // ------------------------------------------------------ traceability
    if (traced.length) {
        out.push(
            '### Requirement → test case → test',
            '',
            'Each node opens its note. A dotted edge marked "stale" is a test built from older text.',
            '',
        );
        const lines = ['```mermaid', 'flowchart LR'];
        const nodes = new Set<string>();
        const caseByName = new Map(testCases.map((tc) => [tc.name, tc]));
        for (const module of moduleNames) {
            const moduleTests = traced.filter((test) =>
                test.covers.some((id) => caseByName.get(id)?.module === module),
            );
            if (!moduleTests.length) continue;
            lines.push(
                `    subgraph ${nodeId('M', module)}[${label(modules.get(module) ?? module)}]`,
                // A subgraph lays out top-down unless told otherwise.
                '        direction LR',
            );
            for (const test of moduleTests) {
                for (const id of test.covers.filter((c) => caseByName.get(c)?.module === module)) {
                    const requirement = caseByName.get(id)?.requirement ?? '';
                    lines.push(
                        `        ${nodeId('R', requirement)}[${label(requirement)}] --> ` +
                            `${nodeId('C', id)}[${label(id)}] ${test.stale.includes(id) ? '-. stale .->' : '-->'} ` +
                            `${nodeId('T', test.note)}[${label(test.note)}]`,
                    );
                    nodes
                        .add(nodeId('R', requirement))
                        .add(nodeId('C', id))
                        .add(nodeId('T', test.note));
                }
            }
            lines.push('    end');
        }
        // Obsidian turns a node whose text names a note into a link to it.
        lines.push(`    class ${[...nodes].join(',')} internal-link;`, '```');
        out.push(...lines, '');
    }

    // ------------------------------------------------------------ lists
    out.push('## Worklists', '');
    const uncovered = requirements.filter((r) => !coveredRequirements.has(r.name));
    const lists: [string, string, string[]][] = [
        [
            'warning',
            `Stale tests (${stale.length})`,
            stale.map(
                (test) =>
                    `${link(test.note)} — built from older text of ${test.stale.map((id) => link(id)).join(', ')}`,
            ),
        ],
        [
            'todo',
            `Requirements with no automated test (${uncovered.length})`,
            uncovered.map((r) => link(r.name)),
        ],
        [
            'note',
            `Tests that cover no test case (${tests.length - traced.length})`,
            tests.filter((test) => !test.covers.length).map((test) => link(test.note)),
        ],
        [
            'info',
            `Tests marked fixme or skip (${notRunning.length})`,
            notRunning.map((test) => `${link(test.note)} — ${test.mode}`),
        ],
    ];
    for (const [kind, title, items] of lists) {
        if (items.length) out.push(callout(kind, title, items), '');
    }
    return `${out.join('\n').trimEnd()}\n`;
}
